version : '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: "always"
    ports:
      - "5001:80"
    links:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      
      



  


